### ISSUE TITLE
if a symlink is used instead of a folder  in "custom subdirectory" the addon reports the file already exists instead of offering to download it

### ISSUE THREAD

**Issue by Selth** [cheeplusplus/faextender-chrome#15]
I tried to use a symlink to point ~/Downloads/FurAffinity to /data/FurAffinity but this does not work at all. instead, the addon is showing that the file "already exists"

this is in 3.2.0.

**Comment by AndrewNeo** [comment]
Can you open the [Browser Console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) and get the error message it gives when you try to save a file? Unfortunately I have basically zero control over this so I don't know if I can do anything about it, but I'd like what it's doing.

**Comment by Selth** [comment]
I've been able to test it again in FF56 on fedora using version 3.2.1.
I'm pleased to say that this issue can no longer be reproduced with those versions of firefox and the extension - the symlink is used, the subfolder for the artist used and the file created.

**Comment by Selth** [comment]
I've been able to test it again in FF56 on fedora using version 3.2.1.
I'm pleased to say that this issue can no longer be reproduced with those versions of firefox and the extension - the symlink is used, the subfolder for the artist used and the file created. 
it'd be nice to have auto download back in a new update :)
