### ISSUE TITLE
Open images in tabs by type + Auto-download

### ISSUE THREAD

**Issue by Holycleric** [cheeplusplus/faextender-chrome#25]
Hi,
I'd like to suggest a new feature that should be pretty easy to introduce. In a previous version I was able with a friend to make it work but now it's beyond our skills.
One thing is to split the "Open images in tabs" in 3 different buttons:
- Open all images in tabs
- Open General images in tabs
- Open Mature and Adult images in tabs
The other one is to add an option to trigger automatically the "Download Now" function when the page loading is complete.

With this two upgrade will be possibile to, for instance, open all Mature and Adult image in the New Submissions section page and automatically download them.

Thanks :)

**Comment by AndrewNeo** [comment]
Auto download will not be a feature due to how the browser treats duplicate files, this has been stated in other bugs. As for the split open in tabs, I think it crowds the UI a little too much. I'd be willing to take a patch with the change hidden behind an option flag, however.

**Comment by Holycleric** [comment]
I'm very sorry to hear this :(
Auto-download feature implemented by my friend used to work great but I can't use that version anymore since both the browser version and extension are not safe anymore. Are you sure there isn't a safe way to do it? The issue is because it replace files with the same name or just keep downloading with (2), (3), etc version of the same file?

The option to split open tab hidden with an option flag sound great though 👍 
Thanks
