### ISSUE TITLE
[Feature Request] Download file as a favorite/exceptional file

### ISSUE THREAD

**Issue by sbobbo** [cheeplusplus/faextender-chrome#26]
I'd like to request a feature. I'd like a separate download button(like "Download Now as Favorite") for images that either downloads them to a separate directory, or adds a configurable prefix to the file.

As things stand now, when I download a file, if it's a top tier image, I rename the file and add "__" as a prefix. I'm just looking to automate that a bit. I am not worried at all about the website's built in favorites feature.

Thanks.

**Comment by cheeplusplus** [comment]
I don't think this is a feature that the extension is going to accept at this time.
